# fly.toml app configuration file generated for edupapers-pdf-processor
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "edupapers-pdf-processor"
primary_region = "ord"

[build]

[env]
  PYTHONUNBUFFERED = "1"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[processes]
  app = "gunicorn --bind=0.0.0.0:8000 --workers=1 --timeout=300 wsgi:app"

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

[deploy]
  release_command = "echo 'Deployment complete'"
